# Assignment Details
In this assignment, you will conduct a guided exploration over the Healthcare stroke dataset. You will learn and use some of the most common exploration/aggregation/descriptive operations. This should also help you learn most of the key functionalities in R.

You will also learn how to use visualization libraries to identify patterns in data that will help in your further data analysis. You will also explore most popular chart types and how to use different libraries and styles to make your visualizations more attractive.


## Reading Dataset


#### Note:-
For execution of this file , the dataset 'healthcare_stroke_dataset.csv' must be in the same folder as this ipynb file

Below code attaches the csv dataset file to R dataframe named as "block"

In [14]:
# loading the dataset
block <- read.csv('healthcare_stroke_dataset.csv', stringsAsFactors = F)
head(block,5)

  id    date       gender age hypertension heart_disease ever_married
1  9046 12/30/2020 Male   67  0            1             Yes
2 51676 8/18/2020  Female 61  0            0             Yes
3 31112 3/5/2020   Male   80  0            1             Yes
4 60182 7/8/2020   Female 49  0            0             Yes
5  1665 6/5/2020   Female 79  1            0             Yes
  work_type     Residence_type avg_glucose_level bmi  smoking_status  stroke
1 Private       Urban          228.69            36.6 formerly smoked 1
2 Self-employed Rural          202.21              NA never smoked    1
3 Private       Rural          105.92            32.5 never smoked    1
4 Private       Urban          171.23            34.4 smokes          1
5 Self-employed Rural          174.12            24.0 never smoked    1


# Preproccesing the Data

In [16]:
# looking at missing values, # orwos and columns & overall summary
row.has.na <- apply(block,1,function(x){any(is.na(x))})
cat("Actual empty values in the given dataset\n",sum(row.has.na))
cat("\nNumber of rows and columns in the dataset are -")
dim(block)
cat("\nsummary of the given dataset")
summary(block)

Actual empty values in the given dataset
 201
Number of rows and columns in the dataset are -

[1] 5110   13

summary of the given dataset

       id            date              gender               age
 Min.   :   67   Length:5110        Length:5110        Min.   : 0.08
 1st Qu.:17741   Class :character   Class :character   1st Qu.:25.00
 Median :36932   Mode  :character   Mode  :character   Median :45.00
 Mean   :36518                                         Mean   :43.23
 3rd Qu.:54682                                         3rd Qu.:61.00
 Max.   :72940                                         Max.   :82.00

  hypertension     heart_disease     ever_married        work_type
 Min.   :0.00000   Min.   :0.00000   Length:5110        Length:5110
 1st Qu.:0.00000   1st Qu.:0.00000   Class :character   Class :character
 Median :0.00000   Median :0.00000   Mode  :character   Mode  :character
 Mean   :0.09746   Mean   :0.05401
 3rd Qu.:0.00000   3rd Qu.:0.00000
 Max.   :1.00000   Max.   :1.00000

 Residence_type     avg_glucose_level      bmi        smoking_status
 Length:5110        Min.   : 55.12    Min.   :10.30   Length:5110
 Class :character   1st Qu.: 77.25    1st Qu.:23.50   Class :character
 Mode  :character   Median : 91.89    Median :28.10   Mode  :character
                    Mean   :106.15    Mean   :28.89
                    3rd Qu.:114.09    3rd Qu.:33.10
                    Max.   :271.74    Max.   :97.60
                                      NA's   :201
     stroke
 Min.   :0.00000
 1st Qu.:0.00000
 Median :0.00000
 Mean   :0.04873
 3rd Qu.:0.00000
 Max.   :1.00000

In [3]:
# replacing missing values
block <- block[!row.has.na,]
row.has.na <- apply(block,1,function(x){any(is.na(x))})
cat("\nTotal Empty values in the dataset after modification\n",sum(row.has.na))

Total Empty values in the dataset after modification
 0

In [4]:
# factorizing the heart_disease & hypertension variables
block$heart_disease <- factor(block$heart_disease, levels = c(0,1), labels =c('No','Yes'))
block$hypertension <- factor(block$hypertension,levels = c(0,1), labels = c('No','Yes'))
summary(block)

       id            date              gender               age
 Min.   :   77   Length:4909        Length:4909        Min.   : 0.08
 1st Qu.:18605   Class :character   Class :character   1st Qu.:25.00
 Median :37608   Mode  :character   Mode  :character   Median :44.00
 Mean   :37064                                         Mean   :42.87
 3rd Qu.:55220                                         3rd Qu.:60.00
 Max.   :72940                                         Max.   :82.00
 hypertension heart_disease ever_married        work_type
 No :4458     No :4666      Length:4909        Length:4909
 Yes: 451     Yes: 243      Class :character   Class :character
                            Mode  :character   Mode  :character



 Residence_type     avg_glucose_level      bmi        smoking_status
 Length:4909        Min.   : 55.12    Min.   :10.30   Length:4909
 Class :character   1st Qu.: 77.07    1st Qu.:23.50   Class :character
 Mode  :character   Median : 91.68    Median :28.10   Mode  :character
                    Mean   :105.31    Mean   :28.89
                    3rd Qu.:113.57    3rd Qu.:33.10
                    Max.   :271.74    Max.   :97.60
     stroke
 Min.   :0.00000
 1st Qu.:0.00000
 Median :0.00000
 Mean   :0.04257
 3rd Qu.:0.00000
 Max.   :1.00000


# Task 1: Statistical Exploratory Data Analysis
Let us start with getting know the dataset. Your first task will be to get some basic information by using Pandas features.

In [5]:
#For each task below, look for a R function to do the task.
#Replace None in each task with your code.


#Task 1-a: Find the number of rows and columns in the block data frame.

details<-dim(block)  # Syntax to display details of data frame to give count of row and columns
cat("\n-->Task 1-a: Number of rows and columns  of block data frame are: \n",details)



#Task 1-b: Find and print the descriptive detail of (count, min,max,avg,mean,top,freq etc) for given dataset 
details<-summary(block)     #Syntax to display details of data frame as a summary
cat("\n-->Task 1-b: Descriptive details of the dataset are\n")
details


#Task 1-c: Print ALL the unique values of work_type,smoking_status and Residence_type columns.
cat("\n-->Task 1-c: Print ALL the unique values of work_type,smoking_status and Residence_type columns:\n")
unique(block$work_type)
unique(block$smoking_status)
unique(block$Residence_type)

-->Task 1-a: Number of rows and columns  of block data frame are:
 4909 13
-->Task 1-b: Descriptive details of the dataset are

       id            date              gender               age
 Min.   :   77   Length:4909        Length:4909        Min.   : 0.08
 1st Qu.:18605   Class :character   Class :character   1st Qu.:25.00
 Median :37608   Mode  :character   Mode  :character   Median :44.00
 Mean   :37064                                         Mean   :42.87
 3rd Qu.:55220                                         3rd Qu.:60.00
 Max.   :72940                                         Max.   :82.00
 hypertension heart_disease ever_married        work_type
 No :4458     No :4666      Length:4909        Length:4909
 Yes: 451     Yes: 243      Class :character   Class :character
                            Mode  :character   Mode  :character



 Residence_type     avg_glucose_level      bmi        smoking_status
 Length:4909        Min.   : 55.12    Min.   :10.30   Length:4909
 Class :character   1st Qu.: 77.07    1st Qu.:23.50   Class :character
 Mode  :character   Median : 91.68    Median :28.10   Mode  :character
                    Mean   :105.31    Mean   :28.89
                    3rd Qu.:113.57    3rd Qu.:33.10
                    Max.   :271.74    Max.   :97.60
     stroke
 Min.   :0.00000
 1st Qu.:0.00000
 Median :0.00000
 Mean   :0.04257
 3rd Qu.:0.00000
 Max.   :1.00000

-->Task 1-c: Print ALL the unique values of work_type,smoking_status and Residence_type columns:

[1] "Private"       "Self-employed" "Govt_job"      "children"
[5] "Never_worked"

[1] "formerly smoked" "never smoked"    "smokes"          "-"

[1] "Urban" "Rural"



# Task 2: Aggregation & Filtering & Rank
In this task, we will perform some very high level aggregation and filtering operations. 
Then, we will apply ranking on the results for some tasks. 
Pandas has a convenient and powerful syntax for aggregation, filtering, and ranking. 
DO NOT write a for loop.

In [12]:


#Task 2-a: Ascertain the highest avg_glucose_level achieved by different ages.
cat("\n-->Task 2-a:Highest avg_glucose_level  for every age is listed below\n")

aggregate(block$avg_glucose_level, by = list("different ages"=block$age,"id Num"=block$id),max)




#Task 2-b:Rank all the movies based on rating in a year where minimum number of movies are released and maximum number of movies released.
cat("\n>-Task 2-b:Listed below are id ordered according to their bmi with the LEAST age \n")
uniqv <- unique(block$age)
min_age<-uniqv[which.min(tabulate(match(block$age, uniqv)))]
cat("\n LEAST age is",min_age)
cat("\n")
newdata <- subset(block, age == min_age)
rankeddata <-newdata[order(newdata$bmi),]
rankeddata

# cat("\n>-Task 2-b:Listed below are id ordered according to their bmi in the with the least age \n")
cat("\n>-Task 2-b:Listed below are id ordered according to their bmi with the HIGHEST age \n")
uniqv <- unique(block$age)
max_age<-uniqv[which.max(tabulate(match(block$age, uniqv)))]
cat("\n HIGHEST age is",max_age)
cat("\n")
newdata <- subset(block, age == max_age)
rankeddata <-newdata[order(newdata$bmi),]
rankeddata

-->Task 2-a:Highest avg_glucose_level  for every age is listed below

     different ages id Num x
1    13              77     85.81
2    55              84     89.17
3    42              91     98.53
4    31              99    108.89
5    24             129     97.55
6    33             156     86.97
7    20             163     94.67
8    20             187     84.07
9    43             205     88.23
10   81             210     91.54
11   59             239    246.53
12    4             242     98.56
13   31             247     72.60
14   79             259    198.79
15   45             315     65.42
16   79             321     71.98
17   43             338    110.32
18   65             354     72.49
19    8             355     96.43
20   58             364    105.74
21   44             365     69.48
22   78             394     75.19
23   48             452    173.14
24   37             458     72.09
25   46             464     78.44
26   59             479     78.28
27   74             491     74.96
28   28             507     94.15
29   12             530     75.22
30    3             533     94.12
⋮    ⋮              ⋮      ⋮
4880  5             72497  111.92
4881 48             72512   90.38
4882 18             72514  120.58
4883 39             72525   90.31
4884 61             72547   55.26
4885 57             72562   64.37
4886 63             72594   95.29
4887 67             72642   67.79
4888 53             72696   70.51
4889  2             72701  112.66
4890 54             72703   75.52
4891 50             72715  193.80
4892 26             72725   59.67
4893 26             72776   94.24
4894 14             72779  131.77
4895 52             72784  118.46
4896 53             72792   77.94
4897 26             72818   90.54
4898 82             72819  243.59
4899 79             72823   70.35
4900 46             72824   59.05
4901 59             72836   65.98
4902 52             72861   69.30
4903 16             72867   99.49
4904 47             72882   75.30
4905 57             72911  129.54
4906 19             72914   90.57
4907 45             72915  172.33
4908 53             72918   62.55
4909  2             72940  102.92

>-Task 2-b:Listed below are id ordered according to their bmi with the LEAST age

 LEAST age is 0.4

     id    date       gender age hypertension heart_disease ever_married
1601 40544 12/16/2020 Male   0.4 No           No            No
4582 15728 3/8/2020   Female 0.4 No           No            No
     work_type Residence_type avg_glucose_level bmi  smoking_status stroke
1601 children  Urban          109.56            14.3 -              0
4582 children  Rural           85.65            17.4 -              0

>-Task 2-b:Listed below are id ordered according to their bmi with the HIGHEST age

 HIGHEST age is 78

     id    date       gender age hypertension heart_disease ever_married
1814 42465 10/31/2020 Female 78  Yes          No            Yes
2011 26247 3/13/2020  Female 78  No           No            Yes
1449 49341 6/22/2020  Female 78  No           No            Yes
249  43424 8/20/2020  Female 78  No           No            Yes
132  16817 10/31/2020 Female 78  Yes          No            No
2604 32445 10/24/2020 Female 78  No           No            Yes
4449 69010 5/1/2020   Male   78  No           No            Yes
2488 44325 12/24/2020 Male   78  No           No            Yes
1972 48775 2/27/2020  Female 78  Yes          No            Yes
2180 66677 10/20/2020 Male   78  No           No            Yes
3784 11250 3/4/2020   Male   78  No           No            Yes
2577 63457 7/29/2020  Female 78  No           Yes           No
2827 21162 11/8/2020  Female 78  No           No            Yes
2638  2005 9/13/2020  Male   78  No           Yes           Yes
166  42899 6/2/2020   Male   78  No           No            Yes
3034 21192 4/19/2020  Female 78  No           No            Yes
41    4651 7/13/2020  Male   78  No           No            Yes
66   17013 8/29/2020  Male   78  Yes          No            No
3681  8614 3/20/2020  Male   78  No           Yes           Yes
4437  5987 10/5/2020  Female 78  No           No            Yes
10   60491 6/22/2020  Female 78  No           No            Yes
3751 68721 6/4/2020   Female 78  No           No            Yes
4615 56425 9/28/2020  Female 78  No           No            Yes
3906  2544 10/27/2020 Male   78  No           No            Yes
2337  9026 10/22/2020 Female 78  Yes          No            Yes
148  62861 9/30/2020  Female 78  No           No            Yes
406  37031 4/5/2020   Female 78  No           Yes           Yes
4186 54871 10/20/2020 Female 78  No           No            Yes
178  36841 8/7/2020   Male   78  Yes          No            Yes
4097 15135 8/4/2020   Female 78  No           Yes           Yes
⋮    ⋮     ⋮          ⋮      ⋮   ⋮            ⋮             ⋮
3233 20375 11/21/2020 Female 78  No           No            Yes
2434 22136 5/11/2020  Male   78  Yes          Yes           No
332  65836 6/29/2020  Female 78  Yes          No            Yes
1853 28913 8/16/2020  Male   78  No           No            Yes
753  30550 6/4/2020   Female 78  No           No            No
3149  6032 5/3/2020   Male   78  No           No            Yes
204  28484 4/23/2020  Female 78  No           No            Yes
3214 32602 2/1/2020   Male   78  No           Yes           Yes
1382 62272 9/11/2020  Female 78  No           No            Yes
3633 61333 9/5/2020   Female 78  No           No            No
4130 11312 7/26/2020  Female 78  No           No            Yes
4723 54395 5/24/2020  Female 78  Yes          No            Yes
4484 62798 3/6/2020   Female 78  Yes          No            Yes
96    2458 2/11/2020  Female 78  No           No            Yes
206  51314 12/2/2020  Female 78  No           No            Yes
1777 25138 6/20/2020  Female 78  Yes          No            Yes
209  54921 5/3/2020   Male   78  Yes          No            Yes
4681 16136 5/9/2020   Female 78  No           No            Yes
4709 18263 11/9/2020  Female 78  No           No            Yes
1415 47622 8/22/2020  Male   78  No           Yes           Yes
315  11120 10/24/2020 Female 78  Yes          No            Yes
1811 38242 9/28/2020  Female 78  No           Yes           Yes
1523 23836 4/26/2020  Male   78  No           No            Yes
4298 50410 9/6/2020   Female 78  No           No            No
302  43454 4/30/2020  Female 78  No           No            No
4735 54022 6/11/2020  Female 78  No           No            Yes
1860 59250 3/8/2020   Female 78  No           No            Yes
3429 57288 10/25/2020 Female 78  No           No            Yes
1738 54353 1/22/2020  Female 78  Yes          Yes           Yes
164  20426 4/27/2020  Female 78  Yes          No            No
     work_type     Residence_type avg_glucose_level bmi  smoking_status  stroke
1814 Private       Rural           58.66            16.4 never smoked    0
2011 Private       Rural           95.37            17.3 -               0
1449 Private       Rural          154.75            17.6 never smoked    0
249  Private       Rural           78.81            19.6 -               1
132  Private       Urban          130.54            20.1 never smoked    1
2604 Self-employed Urban           79.55            21.1 formerly smoked 0
4449 Private       Rural           83.20            21.2 formerly smoked 0
2488 Self-employed Rural          126.39            21.3 smokes          0
1972 Self-employed Rural          201.07            21.8 -               0
2180 Private       Rural           80.09            21.8 never smoked    0
3784 Self-employed Rural           93.85            22.7 formerly smoked 0
2577 Self-employed Urban          110.78            22.9 never smoked    0
2827 Self-employed Rural           81.68            23.0 -               0
2638 Self-employed Urban          169.43            23.5 formerly smoked 0
166  Self-employed Urban          133.19            23.6 formerly smoked 1
3034 Private       Urban           93.15            23.6 -               0
41   Private       Rural           78.03            23.9 formerly smoked 1
66   Private       Urban          113.01            24.0 never smoked    1
3681 Self-employed Urban          101.53            24.1 formerly smoked 0
4437 Private       Urban           89.42            24.1 never smoked    0
10   Private       Urban           58.57            24.2 -               1
3751 Private       Rural          133.13            24.2 -               0
4615 Govt_job      Rural           61.38            24.3 -               0
3906 Private       Urban          208.85            24.4 formerly smoked 0
2337 Self-employed Urban          191.33            24.5 never smoked    0
148  Private       Urban           67.29            24.6 never smoked    1
406  Govt_job      Urban           70.21            24.8 never smoked    0
4186 Private       Urban          119.13            25.0 never smoked    0
178  Self-employed Rural           56.11            25.5 formerly smoked 1
4097 Private       Rural          221.06            25.5 formerly smoked 0
⋮    ⋮             ⋮              ⋮                 ⋮    ⋮               ⋮
3233 Private       Urban           78.29            30.1 formerly smoked 0
2434 Self-employed Urban           92.90            30.4 smokes          0
332  Private       Urban          182.20            30.5 formerly smoked 0
1853 Private       Rural          100.09            30.5 -               0
753  Private       Urban          103.86            30.6 -               0
3149 Self-employed Urban          201.58            30.6 -               0
204  Self-employed Rural          109.47            30.8 never smoked    1
3214 Self-employed Urban           87.77            30.8 -               0
1382 Private       Urban          119.03            31.0 never smoked    0
3633 Self-employed Rural           68.35            31.4 -               0
4130 Self-employed Rural          208.99            31.4 formerly smoked 0
4723 Self-employed Rural          152.38            31.8 never smoked    0
4484 Private       Rural          100.54            32.1 smokes          0
96   Private       Rural          235.63            32.3 never smoked    1
206  Private       Urban          106.74            33.0 formerly smoked 1
1777 Private       Rural           91.63            33.5 smokes          0
209  Self-employed Rural          134.80            33.6 -               1
4681 Self-employed Urban           84.21            33.7 never smoked    0
4709 Self-employed Urban          234.06            33.7 never smoked    0
1415 Self-employed Urban          228.70            34.0 -               0
315  Private       Urban          218.46            34.3 never smoked    0
1811 Self-employed Rural           88.90            34.3 -               0
1523 Private       Urban           90.43            34.4 formerly smoked 0
4298 Govt_job      Rural           76.64            34.6 never smoked    0
302  Self-employed Urban          137.74            34.9 formerly smoked 0
4735 Self-employed Rural           67.90            35.3 never smoked    0
1860 Govt_job      Urban           58.88            35.8 -               0
3429 Private       Rural           99.84            36.6 never smoked    0
1738 Private       Urban          227.16            41.7 never smoked    0
164  Private       Urban          203.87            45.7 never smoked    1